---
title: "Math156-Project"
author: "Huy Nguyen"
date: "5/22/2022"
output: pdf_document
---

```{r}
library(tidyverse)
library(readr)
```

## Load data

```{r}
train <- suppressMessages(suppressWarnings(read_csv("/Users/huynguyen/Downloads/Math 156/train.csv"))) #training data
train_no_id <- train[,-c(1,2)] #rid of index and id
test <- suppressMessages(suppressWarnings(read_csv("/Users/huynguyen/Downloads/Math 156/test.csv"))) #testing data
test_no_id <- test[,-c(1,2)]

#deal with categorical variables
train_no_id$Gender <- factor(train_no_id$Gender)
train_no_id$`Customer Type` <- factor(train_no_id$`Customer Type`)
train_no_id$`Type of Travel` <- factor(train_no_id$`Type of Travel`)
train_no_id$Class <- factor(train_no_id$Class)
train_no_id$`Inflight wifi service` <- factor(train_no_id$`Inflight wifi service`)
train_no_id$`Departure/Arrival time convenient` <- factor(train_no_id$`Departure/Arrival time convenient`)
train_no_id$`Ease of Online booking` <- factor(train_no_id$`Ease of Online booking`)
train_no_id$`Gate location` <- factor(train_no_id$`Gate location`)
train_no_id$`Food and drink` <- factor(train_no_id$`Food and drink`)
train_no_id$`Online boarding` <- factor(train_no_id$`Online boarding`)
train_no_id$`Seat comfort` <- factor(train_no_id$`Seat comfort`)
train_no_id$`Inflight entertainment` <- factor(train_no_id$`Inflight entertainment`)
train_no_id$`On-board service` <- factor(train_no_id$`On-board service`)
train_no_id$`Leg room service` <- factor(train_no_id$`Leg room service`)
train_no_id$`Baggage handling` <- factor(train_no_id$`Baggage handling`)
train_no_id$`Checkin service` <- factor(train_no_id$`Checkin service`)
train_no_id$`Inflight service` <- factor(train_no_id$`Inflight service`)
train_no_id$Cleanliness <- factor(train_no_id$Cleanliness)


test_no_id$Gender <- factor(test_no_id$Gender)
test_no_id$`Customer Type` <- factor(test_no_id$`Customer Type`)
test_no_id$`Type of Travel` <- factor(test_no_id$`Type of Travel`)
test_no_id$Class <- factor(test_no_id$Class)
test_no_id$`Inflight wifi service` <- factor(test_no_id$`Inflight wifi service`)
test_no_id$`Departure/Arrival time convenient` <- factor(test_no_id$`Departure/Arrival time convenient`)
test_no_id$`Ease of Online booking` <- factor(test_no_id$`Ease of Online booking`)
test_no_id$`Gate location` <- factor(test_no_id$`Gate location`)
test_no_id$`Food and drink` <- factor(test_no_id$`Food and drink`)
test_no_id$`Online boarding` <- factor(test_no_id$`Online boarding`)
test_no_id$`Seat comfort` <- factor(test_no_id$`Seat comfort`)
test_no_id$`Inflight entertainment` <- factor(test_no_id$`Inflight entertainment`)
test_no_id$`On-board service` <- factor(test_no_id$`On-board service`)
test_no_id$`Leg room service` <- factor(test_no_id$`Leg room service`)
test_no_id$`Baggage handling` <- factor(test_no_id$`Baggage handling`)
test_no_id$`Checkin service` <- factor(test_no_id$`Checkin service`)
test_no_id$`Inflight service` <- factor(test_no_id$`Inflight service`)
test_no_id$Cleanliness <- factor(test_no_id$Cleanliness)

library(ggplot2)
library(naniar)


gg_miss_var(train_no_id)

```

## Preliminary Plots

```{r}
length(is.na(train_no_id)) # Number of NAs in train
length(is.na(test_no_id)) #Number of NAs in test
set.seed(123) #Set seed to 123
#plot()
```

```{r}
# Numerical variables
library(gridExtra)
g1<-ggplot(train_no_id, aes(x = Age))+geom_density(aes(color = satisfaction)) #definitely in model
g2<-ggplot(train_no_id, aes(x = `Flight Distance`))+geom_density(aes(color = satisfaction)) # may not in model
g3<-ggplot(train_no_id, aes(x = `Departure Delay in Minutes`))+geom_density(aes(color = satisfaction)) # not in model
g4<-ggplot(train_no_id, aes(x = `Arrival Delay in Minutes`))+geom_density(aes(color = satisfaction)) # not in model
#grid.arrange(g1,g2,ncol=2)
g1
g2
g3
g4
```

```{r}
# categorical variable
g5<-ggplot(train_no_id, aes(x=Gender,fill=satisfaction)) + geom_bar() # not in model
g6<-ggplot(train_no_id, aes(x=`Customer Type`,fill=satisfaction)) + geom_bar() # in model
g7<-ggplot(train_no_id, aes(x=`Type of Travel`,fill=satisfaction)) + geom_bar() # in model
g8<-ggplot(train_no_id, aes(x=Class,fill=satisfaction)) + geom_bar() # in model
g9<-ggplot(train_no_id, aes(x=`Inflight wifi service`,fill=satisfaction)) + geom_bar() # in model
g10<-ggplot(train_no_id, aes(x=`Departure/Arrival time convenient`,fill=satisfaction)) + geom_bar() # in model
g11<-ggplot(train_no_id, aes(x=`Ease of Online booking`,fill=satisfaction)) + geom_bar() # in model
g12<-ggplot(train_no_id, aes(x=`Gate location`,fill=satisfaction)) + geom_bar() # in model
g13<-ggplot(train_no_id, aes(x=`Food and drink`,fill=satisfaction)) + geom_bar() # in model
g14<-ggplot(train_no_id, aes(x=`Online boarding`,fill=satisfaction)) + geom_bar() # in model
g15<-ggplot(train_no_id, aes(x=`Seat comfort`,fill=satisfaction)) + geom_bar() # in model
g16<-ggplot(train_no_id, aes(x=`Inflight entertainment`,fill=satisfaction)) + geom_bar() # in model
g17<-ggplot(train_no_id, aes(x=`On-board service`,fill=satisfaction)) + geom_bar() # in model
g18<-ggplot(train_no_id, aes(x=`Leg room service`,fill=satisfaction)) + geom_bar() # in model
g19<-ggplot(train_no_id, aes(x=`Baggage handling`,fill=satisfaction)) + geom_bar() # in model
g20<-ggplot(train_no_id, aes(x=`Checkin service`,fill=satisfaction)) + geom_bar() # in model
g21<-ggplot(train_no_id, aes(x=`Inflight service`,fill=satisfaction)) + geom_bar() # in model
g22<-ggplot(train_no_id, aes(x=Cleanliness,fill=satisfaction)) + geom_bar() # in model
grid.arrange(g5,g6,ncol=1)
grid.arrange(g7,g8,ncol=1)
grid.arrange(g9,g10,ncol=1)
grid.arrange(g11,g12,ncol=1)
grid.arrange(g13,g14,ncol=1)
grid.arrange(g15,g16,ncol=1)
grid.arrange(g17,g18,ncol=1)
grid.arrange(g19,g20,ncol=1)
grid.arrange(g21,g22,ncol=1)

```

# Logistic Model

```{r}
library(leaps)
train_removeDelay <- train_no_id[-c(21,22)]
train_removeDelay <- train_removeDelay[rowSums(is.na(train_removeDelay)) == 0, ]
#Remove Delays since not important + No more NAs
test_removeDelay <- test_no_id[-c(21,22)]
#train_NoNA <- train_no_id[rowSums(is.na(train_no_id)) == 0, ]
# mfull<-glm(as.factor(satisfaction)~.,data=train_removeDelay,family=binomial())
# bBIC=step(mfull,direction="backward",log=nrow(train_removeDelay)) #Backward BIC
# bBIC
glm.mod <- glm(as.factor(satisfaction) ~ ., data = train_removeDelay,
               family=binomial())

plot(glm.mod)

summary(glm.mod)
attributes(alias(glm.mod)$Complete)$dimnames[[1]] # features causing multicollinearity
# can remove two of three: checkin, inflight, and cleanliness
```

# Predict on test model:

```{r,warning=FALSE}
test_feat <- test_removeDelay[,-c(21)]
dim(test_feat) # 25976 rows
predtest <- predict(glm.mod,test_feat,type="response")
glm.predtest=rep("satisfied",25976)
glm.predtest[predtest<0.5]="neutral or dissatisfied"
mean(glm.predtest == factor(test_removeDelay$satisfaction))
table(glm.predtest,factor(test_removeDelay$satisfaction))
```


# Tree model

```{r}
library(tree)
colnames(train_removeDelay) <- make.names(colnames(train_removeDelay))
colnames(test_removeDelay) <- make.names(colnames(test_removeDelay))
tree.m=tree(as.factor(satisfaction)~., train_removeDelay)
tree.pred=predict(tree.m, test_removeDelay, type="class")
table(tree.pred,test_removeDelay$satisfaction)
paste('Testing Accuracy:', (13532+9779)/26976)

cv.tree = cv.tree(tree.m,FUN=prune.misclass)
par(mfrow=c(1,2))
plot(cv.tree$size,cv.tree$dev,type="b")
plot(cv.tree$k,cv.tree$dev,type="b")

plot(tree.m)
text(tree.m,pretty=0,cex = 0.5, srt = 270)

prune.tree=prune.misclass(tree.m,best=5)
plot(prune.tree)
text(prune.tree,pretty=0,cex = 0.6)

tree.pred.prune=predict(prune.tree,test_removeDelay,type="class")
table(tree.pred.prune,test_removeDelay$satisfaction)
paste('testing accuracy:', (12562+10375)/26976, ', so we did better than full tree')
```


# PCA

```{r}
pcaTrain <- princomp(train[,c(5,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22)]) #1,2,3,4,6,7,23,24,25
pcaTest <- princomp(test[,c(5,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22)])

# ONLY PC1 is enough!!!!

newTrain <- cbind(train,pcaTrain$scores) 
newTrain <-newTrain[,-c(5,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22)]
# may use these standardized components to improve logistic
newTest <- cbind(test,pcaTest$scores)
newTest <-newTest[,-c(5,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22)]


trainpca <-data.frame(group = newTrain$satisfaction, PC1 = newTrain$Comp.1, PC2 = newTrain$Comp.2)
p<-ggplot(trainpca,aes(x=PC1,y=PC2,color=group))
p<-p+geom_point()+theme_bw()+ggtitle("PCA Plane Training Data") + xlab("PC1 - 99.9%") + ylab("PC2") + 
  theme(plot.title = element_text(hjust = 0.5),rect=element_rect(fill='transparent'))
p


testpca <-data.frame(group = newTest$satisfaction,PC1 = newTest$Comp.1, PC2 = newTest$Comp.2)
p1<-ggplot(testpca,aes(x=PC1,y=PC2,color=group))
p1<-p1+geom_point()+theme_bw()+ggtitle("PCA Plane Testing Data") + xlab("PC1 - 99.9%") + ylab("PC2") + 
  theme(plot.title = element_text(hjust = 0.5),rect=element_rect(fill='transparent'))
p1
```
# Logistic + PCA

```{r}
newTrain$Gender <- factor(newTrain$Gender)
newTrain$`Customer Type` <- factor(newTrain$`Customer Type`)
newTrain$`Type of Travel` <- factor(newTrain$`Type of Travel`)
newTrain$Class <- factor(newTrain$Class)

newTest$Gender <- factor(newTest$Gender)
newTest$`Customer Type` <- factor(newTest$`Customer Type`)
newTest$`Type of Travel` <- factor(newTest$`Type of Travel`)
newTest$Class <- factor(newTest$Class)


glm.mod.PCA <- glm(as.factor(satisfaction) ~ Comp.1 + Comp.2 + Comp.3 + Comp.4 + Comp.5 + 
                    Comp.6 + Comp.7 + Comp.8 + Comp.9 + Comp.10 + Comp.11 + Comp.12 + 
                    Comp.13 + Comp.14 + Comp.15 + Comp.16 + Gender + `Customer Type` +
                   `Type of Travel` + Class, data = newTrain,
                    family=binomial())
summary(glm.mod.PCA)
predtest.PCA <- predict(glm.mod.PCA,newTest,type="response")
glm.predtest.PCA=rep("satisfied",25976)
glm.predtest.PCA[predtest.PCA<0.5]="neutral or dissatisfied"
mean(glm.predtest.PCA == factor(test_removeDelay$satisfaction))
table(glm.predtest.PCA,factor(test_removeDelay$satisfaction))

plot(glm.mod.PCA)
```